version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.11.0
        environment:
          NODE_ENV: test
          PORT: 3333
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-1-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: "."
          paths:
            - node_modules

  jest_test:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - run: npm run test

workflows:
  build_and_test:
    jobs:
      - build
      - jest_test:
          requires:
            - build
